### ISSUE TITLE
Problems loading 04_Demo

### ISSUE THREAD

**Issue by AndrePasemann** [fgotzens/disaggregator#2]
Hello DemanRegioTeam,

first I want to thank you for your good work! Very usable tool you uploaded here.
Unfortunatly I have a problem loading the time series "ZVE_timeseries_AllRegions_2015.csv"
I get the following error when I run this command 
df_temp = (pd.read_csv(config.data_out('ZVE_timeseries_AllRegions_2015.csv'),
                       engine='c', index_col=0, parse_dates=True,
                       infer_datetime_format=True)
              .pipe(data.transpose_spatiotemporal))
df_temp

ERROR:
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-06822c8d489e> in <module>
      1 df_temp = (pd.read_csv(config.data_out('ZVE_timeseries_AllRegions_2015.csv'),
      2                        engine='c', index_col=0, parse_dates=True,
----> 3                        infer_datetime_format=True)
      4               .pipe(data.transpose_spatiotemporal))
      5 df_temp

~/opt/anaconda3/envs/disaggregator/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

~/opt/anaconda3/envs/disaggregator/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

~/opt/anaconda3/envs/disaggregator/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

~/opt/anaconda3/envs/disaggregator/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

~/opt/anaconda3/envs/disaggregator/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File /Users/admin/Documents/Promotion/Sim/Diss/demand_data/disaggregator-master/disaggregator/../data_out/ZVE_timeseries_AllRegions_2015.csv does not exist: '/Users/admin/Documents/Promotion/Sim/Diss/demand_data/disaggregator-master/disaggregator/../data_out/ZVE_timeseries_AllRegions_2015.csv'

Do I have to create this csv-File first because in the "data_out" folder I couldn't find it.

I thank you for any help! 
All the best
André

**Comment by PVerwiebe** [comment]
Hi Andre, this issue should be fixed now. 
Kind regards
Paul
