### ISSUE TITLE
Error when creating gas demand time series for 2011

### ISSUE THREAD

**Issue by wheitkoetter** [fgotzens/disaggregator#5]
Dear DemandRegioTeam,

thanks for the great work and developing the disaggregator tool.
As part of the [eGon](https://ego-n.org/) project we would also like to use the disaggregator results. At DLR we are responsible for the gas sector.

I executed the [04_Demo_temporal_disaggregations.ipynb](https://github.com/DemandRegioTeam/disaggregator/blob/master/04_Demo_temporal_disaggregations.ipynb) with the standard settings for the year 2015 without having problems.

As we want to use 2011 as weather year in the eGon project, I set base_year: 2011 in [config.yaml](https://github.com/DemandRegioTeam/disaggregator/blob/master/disaggregator/config.yaml).

While `data.elc_consumption_HH_spatiotemporal()` still worked fine, `data.standard_load_profile_gas(typ='MFH')` resulted in the following error meassage: 
File "04_Demo_temporal_disaggregations_v2.py", line 170, in <module>
    df_temp_MFH = data.standard_load_profile_gas(typ='MFH')
  File "C:\Users\heit_wi\disaggregator-master\disaggregator-master\disaggregator\data.py", line 1468, in standard_load_profile_gas
    df_slp = reshape_spatiotemporal(key='slp_H0_1H_gas', **kwargs)
  File "C:\Users\heit_wi\disaggregator-master\disaggregator-master\disaggregator\data.py", line 1831, in reshape_spatiotemporal
    internal_id=internal_id, force_update=force_update)
  File "C:\Users\heit_wi\disaggregator-master\disaggregator-master\disaggregator\data.py", line 1965, in database_get
    return database_raw(query, force_update=force_update)
  File "C:\Users\heit_wi\disaggregator-master\disaggregator-master\disaggregator\config.py", line 108, in database_raw
    raise ValueError('The returned pd.DataFrame is empty!')
ValueError: The returned pd.DataFrame is empty!

Correspondingly, 
`http://opendata.ffe.de:4000/demandregio_temporal?id_temporal=eq.28&&year_weather=eq.2015&&internal_id=eq.{1}`
yields results, when opening it in a browser, while
`http://opendata.ffe.de:4000/demandregio_temporal?id_temporal=eq.28&&year_weather=eq.2011&&internal_id=eq.{1}`
does not yield result data.

Is it thus not possible to generate gas demand time series with the disaggregator tool for 2011 using the current release without changing the code / adding additional wheather data etc.? Or am I doing something wrong?

Thanks in advance!

Best regards

Wilko Heitkötter
DLR Institute of Networked Energy Systems

**Comment by PVerwiebe** [comment]
Dear Wilko,
thank you for pointing this out. You did fine, however the available data did not allow you to calculate any other year at that point. 
I closed the data-gap now by introducing a new function which works similar to the one that is used for the temporal gas demand in CTS. The new function is called `disagg_temporal_gas_households()`. You can find an update on how to use this function in [04_Demo_temporal_disaggregations.ipynb](https://github.com/DemandRegioTeam/disaggregator/blob/master/04_Demo_temporal_disaggregations.ipynb).

Best regards
Paul
TU-Berlin
Energy & Resource Management

**Comment by wheitkoetter** [comment]
Dear Paul,

thanks a lot for fixing! I will try to test it as soon as possible.

Best regards

Wilko
