### ISSUE TITLE
Problems with 04_Demo

### ISSUE THREAD

**Issue by Pyosch** [fgotzens/disaggregator#9]
Dear all,

thanks for providing this nice library. However, when executing the notebook "04_Demo_CTS_Industry_disaggregation_" I get the following error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_22780/222239687.py in <module>
----> 1 ec_CTS = spatial.disagg_CTS_industry(sector='CTS', source='power', use_nuts3code=True)
      2 ec_CTS.head()

~\disaggregator\disaggregator\spatial.py in disagg_CTS_industry(source, sector, use_nuts3code, no_self_gen, **kwargs)
    376     year = kwargs.get('year', cfg['base_year'])
    377     [spez_sv, spez_gv] = generate_specific_consumption_per_branch_and_district(
--> 378         8, 8, no_self_gen, year=year)
    379     if source == 'power':
    380         spez_vb = spez_sv

~\disaggregator\disaggregator\data.py in generate_specific_consumption_per_branch_and_district(iterations_power, iterations_gas, no_self_gen, **kwargs)
    521     year = kwargs.get('year', cfg['base_year'])
    522     [spez_sv, spez_gv, vb_wz, bze_je_lk_wz, df_f_sv_no_self_gen,
--> 523      df_f_gv_no_self_gen] = generate_specific_consumption_per_branch(year=year)
    524     # get latest "Regionalstatistik" from Database
    525     x = True

~\disaggregator\disaggregator\data.py in generate_specific_consumption_per_branch(**kwargs)
    356 
    357     # get number of employees (bze) from database
--> 358     bze_je_lk_wz = pd.DataFrame(employees_per_branch(year=year1))
    359     bze_lk_wz = (pd.DataFrame(0.0, index=bze_je_lk_wz.columns,
    360                               columns=wz_dict().values()))

~\disaggregator\disaggregator\data.py in employees_per_branch(region_code, **kwargs)
   1474     cfg = kwargs.get('cfg', get_config())
   1475     year = kwargs.get('year', cfg['base_year'])
-> 1476     scenario = kwargs.get('scenario', cfg['employees']['scenario'])
   1477     assert scenario in ['Basis', 'Digital', 'Predefined', 'Direct']
   1478 

KeyError: 'employees'

----------------------------------

Do you know how to fix this? So fare I used the example_config.yaml provided. Do I need to extend it in some way?

Best
Pyosch

**Comment by fgotzens** [comment]
Hi Pyosch,
thanks for the nudge! The example_config.yaml had not been updated after making some changes to data.py - this has been done now and should work again!
Regards,
Fabian
